# Generated by Django 5.2.3 on 2025-06-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='reconhecido_por',
            field=models.CharField(default='tablet', max_length=50),
        ),
    ]
