# Generated by Django 5.2.3 on 2025-06-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_presenca_reconhecido_por'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('aluno', 'data')},
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='aula',
        ),
    ]
