# Generated by Django 5.2.3 on 2025-06-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_presenca_unique_together_remove_presenca_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='dia_semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10),
        ),
    ]
